[package]
name = "bcsv-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bcsv = { path = "../../lib/bcsv" }
clap = { version = "4.1", features = ["derive"] }
csv = "1.1"
atty = "0.2"
color-eyre = "0.6"
comfy-table = "6.1"
